### ISSUE TITLE
Linux Server Version doesn't work.

### ISSUE THREAD

**Issue by markusmarkusz** [danielga/gm_luaerror#2]
I just can't use gmsv_luaerror_linux.
```
lua_run print(pcall(require, "luaerror"))
> print(pcall(require, "luaerror"))...
false   Couldn't load module library!
```
Using gmcl_luaerror_linux works.
Can someone tell me why?

**Comment by markusmarkusz** [comment]
It looks like something went wrong when you compiled gmsv_luaerror_linux.
I have compiled the module on my debian server and everything works fine.

**Comment by danielga** [comment]
Fixed by modifying [garrysmod_common](https://github.com/danielga/garrysmod_common/commit/4e9958ecb411439b3d8cd61ef01303c3332cbf13) and recompiling the module.
