### ISSUE TITLE
Can't load module on Linux

### ISSUE THREAD

**Issue by MStruntze** [danielga/gm_luaerror#23]
Hi there.
Using the most recent [release](https://github.com/danielga/gm_luaerror/releases/tag/1.5.0), loading the module on my Ubuntu 16.04 server throws the following errors:

![putty_2018-08-22_11-37-50](https://user-images.githubusercontent.com/638047/44456023-d2ff7280-a5ff-11e8-92fc-567d9b17daa7.png)

**Comment by danielga** [comment]
Can you try the new builds on the same tag? I manually built them and I suspect CI is making bad builds somehow.

**Comment by MStruntze** [comment]
The new build works.
