### ISSUE TITLE
Module not loading on latest ubuntu version

### ISSUE THREAD

**Issue by s980845** [danielga/gm_luaerror#26]
Attempted to load this and wasn't working. I performed this test

require "luaerror"
hook.Add("LuaError","test", function(fullerror)
	print("ooooof")
end)

It returned with 

[ERROR] <color=255,100,100>LuaFoxx<Default>:1: Module not found!
stack traceback:
[C]: in function 'require'
<color=255,100,100>LuaFoxx<Default>:1: in main chunk
[C]: in function 'LUADEV_EXECUTE_FUNCTION'

**Comment by danielga** [comment]
I was unable to reproduce this on Debian (version 9), from which Ubuntu is derived.

Are you sure you placed the right module in the right place?
`gmsv_luaerror_linux.dll` for servers and `gmcl_luaerror_linux.dll` for clients, into `garrysmod/lua/bin`, creating the `bin` directory if it doesn't exist.
