### ISSUE TITLE
gm_luaerror won't work on the incoming release of Garrysmod

### ISSUE THREAD

**Issue by TeddiO** [danielga/gm_luaerror#27]
Pending the next update, the module will load as intended but will fail to catch any errors. This can be confirmed on the latest dev build.

**Comment by TeddiO** [comment]
Update is now out :)

**Comment by danielga** [comment]
I am unable to replicate this on Windows 10, on master Garry's Mod, both client and server. Client singleplayer does seem to have an issue with `HandleClientLuaError` but don't really care about that. Also looked at the function signatures on Linux client and they seemed good.

**Comment by TeddiO** [comment]
I'm not sure if there were any changes from dev to live with Gmod itself, but it does appear to be working for me as well. Apologies for any wasted time I caused you!
