### ISSUE TITLE
x86-64 bit compatibility

### ISSUE THREAD

**Issue by emoyly** [danielga/gm_luaerror#29]
As the x64bit beta branch is increasing in popularity, it would be very useful to be able to actually use it, while keeping track of errors with your wonderful module!

I personally have no experience with C++, so I really have no clue how difficult it would be, but I am hoping that it would become possible in the near future, as we plan to switch our servers onto the 64bit branch.

**Comment by brandonsturgeon** [comment]
+1 on this one, I think it would be a valuable addition. This is the only library that I can find that provides this level of functionality.

**Comment by MStruntze** [comment]
Any updates on this?

**Comment by mtuska** [comment]
+1 would love to see this update. Fantastic to use with sentry.io support.

**Comment by danielga** [comment]
I believe this should be done with [these builds](https://github.com/danielga/gm_luaerror/releases/tag/1.5.3).
