### ISSUE TITLE
unable to create a hook for HandleClientLuaError

### ISSUE THREAD

**Issue by vega0** [danielga/gm_luaerror#30]
require "luaerror2"
	unable to create a hook for HandleClientLuaError
	 1: (message = "unable to create a hook for HandleClientLuaError") [addons/gcompute/lua/gcompute/execution/local/gluaexecutioninstance.lua: 178]
	 2: ("d:\\servers\\garrysmod\\garrysmod\\lua\\bin\\gmsv_luaerror2_win32.dll", { table: 0x2d3df088 }, "unable to create a hook for HandleClientLuaError") [[C]: -1]
	 3:  ("luaerror2", userdata: 0x2d3deef8) [[C]: -1]
	 4: (__param1 = "luaerror2") [[string "*"]: 0]
	 5: xpcall (function (message)) [[C]: -1]
	 6: Start (self = { GCompute.Execution.GLuaExecutionInstance: 0x2d3d91f0 }) [addons/gcompute/lua/gcompute/execution/local/gluaexecutioninstance.lua: 173]
	 7: CreateExecutionInstance (self = { GCompute.Execution.GLuaExecutionContext: 0x2d3c8668 }, code = "require \"luaerror2\"", sourceId = "@repl_0", instanceOptions = 6, callback = nil) [addons/gcompute/lua/gcompute/execution/executioncontext.lua: 56]
	 8: HandleExecutionInstanceCreationRequest0 (self = { GCompute.Execution.RemoteExecutionContextHost: 0x2d3ca0f8 }, connection = { GLib.Net.Connection: 0x2d3d4548 }, inBuffer = { GLib.Net.Layer1.PinnedNetInBuffer: 0x2d3d6f68 }) [addons/gcompute/lua/gcompute/execution/remote/remoteexecutioncontexthost.lua: 94]
	 9: (self = { GCompute.Execution.RemoteExecutionContextHost: 0x2d3ca0f8 }, connection = { GLib.Net.Connection: 0x2d3d4548 }, inBuffer = { GLib.Net.Layer1.PinnedNetInBuffer: 0x2d3d6f68 }) [addons/gcompute/lua/gcompute/execution/remote/remoteexecutioncontexthost.lua: 78]
	10: xpcall (GLib.Error) [[C]: -1]
	11: () [addons/glib/lua/glib/threading/thread.lua: 262]

**Comment by vega0** [comment]
It was on Windows

**Comment by danielga** [comment]
`luaerror2` is deprecated. You're supposed to require `luaerror`.

**Comment by vega0** [comment]
i just named luaerror like luaerror2

**Comment by danielga** [comment]
Seems like you're using the x86-64 branch, but with the 32 bits SRCDS executable. Is this correct? The x86-64 branch is not supported as of yet.
