### ISSUE TITLE
Windows 32 bit: unable to initialize IFileSystem

### ISSUE THREAD

**Issue by Donkie** [danielga/gm_luaerror#32]
I downloaded the latest windows artifact from azure pipelines: https://metamann.visualstudio.com/GitHub%20danielga/_build/results?buildId=112&view=results

Running gmod without any beta branches on a Windows 10 desktop.

I simply get this error when trying to require luaerror, not much else to go on.

**Comment by danielga** [comment]
Please try [these builds](https://github.com/danielga/gm_luaerror/releases/tag/1.5.3).

**Comment by Donkie** [comment]
That seems to have fixed it, thanks!
