### ISSUE TITLE
Crash with latest Garrysmod version

### ISSUE THREAD

**Issue by TeddiO** [danielga/gm_luaerror#36]
With the most recent release (2021.01.22), an error followed by a crash is recorded when using the latest luaerror. 

```
[ERROR] unable to obtain AdvancedLuaErrorReporter
  1. unknown - [C]:-1
   2. require - [C]:-1

**Comment by danielga** [comment]
Something is overriding the value at `debug.getregistry()[1]` with something other than a Lua C function. Honestly, this is very naughty. Can't wait for the moment they remove `debug.getregistry` 😄
