### ISSUE TITLE
Potential crash event with the latest GMod update

### ISSUE THREAD

**Issue by TeddiO** [danielga/gm_luaerror#39]
```Exe version 2021.12.15 (garrysmod)
Exe build: 20:02:11 Dec 14 2021 (8438) (4000)
GMod version 2021.12.14, branch: unknown
Windows 32bit Dedicated Server
```
If an error is thrown before `ISteamHTTP` is available (e.g. close to or on server boot), the server will hang and endlessly consume RAM until the server echos `not enough memory`.

Example error trace: 
```
[ERROR] HTTP failed - ISteamHTTP isn't available!
  1. Post - lua/includes/modules/http.lua:71
   2. v - gamemode/path/that/hooks
    3. unknown - lua/includes/modules/hook.lua:96
     4. HTTP - [C]:-1
 ```

**Comment by TeddiO** [comment]
Additionally after some testing with a vanilla install of GMod, even calling something via an http based function in `GM:Initialize()` is still too early 👀

**Comment by danielga** [comment]
To understand this issue better, is the server hang only happening with the module active? Is that example trace what seems to be causing the hang?

**Comment by danielga** [comment]
Also, can you make a small sample that reproduces the problem, so I can do it locally?

**Comment by TeddiO** [comment]
So it looks like the issue isn't to do with `gm_luaerror` directly, but instead there's an infinite loop when trying to handle a specific scenario.

In this particular scenario the `http.Fetch` (or any `http*` based operation) function is what's actually failing which causes `gm_luaerror` to attempt to handle the newly generated error, ad infinitum leading to an infinite loop.

Below is an example that should work if you dump it in to autorun, but at this point it's not specifically a luaerror issue anymore. 

```
require("luaerror")
hook.Add("LuaError", "Example", 
	http.Fetch("https://google.com")
end)

error("This is an error")
```

**Comment by TeddiO** [comment]
I've got a better example on the way as I think I've isolated it.

**Comment by TeddiO** [comment]
Updated my previous comment with an updated example.

Having `luaerror.EnableCompiletimeDetour` set to `true` or `luaerror.EnableRuntimeDetour` set to true will help facilitate an infinite loop if used in conjunction with a `http` function and `ISteamHTTP` is not yet available.

**Comment by TeddiO** [comment]
I've included an example in gamemode format as well if that's of better / more use to you. 

[crash.zip](https://github.com/danielga/gm_luaerror/files/7722256/crash.zip)

**Comment by danielga** [comment]
I've replicated the problem and it's easy to fix. However, I'm undecided on whether to completely disallow reentrancy or allow a couple loops before stopping.

**Comment by danielga** [comment]
Please try [this build](https://github.com/danielga/gm_luaerror/releases/tag/1.5.7) (when it's done).

**Comment by TeddiO** [comment]
For some reason Windows keeps flagging it as a virus when the download completes (`gmsv_luaerror_win32.dll`)

![image](https://user-images.githubusercontent.com/1713740/146457269-acc8a169-b4d6-4b66-9003-64d14f5aa6c0.png)

**Comment by danielga** [comment]
Tried it on my Windows Defender and it didn't report anything, although VirusTotal reports the same as you. https://www.virustotal.com/gui/file/dcac940d3f6c1bed2e8ca0ee5237943f56c0fec62acb48f4a407a996ae1ffd15

**Comment by danielga** [comment]
Not much I can do, I'm afraid. Detouring and signature scanning seems like relative common things for viruses.

**Comment by TeddiO** [comment]
That's fair, I'll just tell Windows to ignore it, can't help false positives!

**Comment by TeddiO** [comment]
Yep, that works! 🎉

**Comment by danielga** [comment]
Just to put it out there, I went with the no reentrancy route, which means you won't receive `LuaError` hook calls for errors that occurred inside a `LuaError`.
