### ISSUE TITLE
Nothing is working?

### ISSUE THREAD

**Issue by GalaxyOfWaffles** [danielga/gm_luaerror#4]
I downloaded the cl version of the binary hoping to hide errors from the server somehow.
I required it in the client state not the menu state.

luaerror.EnableCompiletimeDetour(true) makes include think the file is empty or something.
I have tried having both of them false one true and both true.

Running script a.lua...
Couldn't include file 'a.lua' (File not found) (<nowhere>)

<code>hook.Add("LuaError","heck",function(...)
print("oh no an error ",...)
end)
hook.Add("ClientLuaError","heck",hook.GetTable()["LuaError"]["heck"])</code>

to trigger an error i am doing:
lua_run_cl -
lua_run_cl wat="
lua_run_cl local n n()

none of them print anything

**Comment by SwadicalRag** [comment]
:+1: nothing is working not even you

**Comment by danielga** [comment]
Fixed in the latest commit.

**Comment by chelog** [comment]
I think it's happening again. Not triggering the hook.

**Comment by danielga** [comment]
I couldn't confirm the error on Windows, everything is working fine. @chelog please open a new issue next time.
