### ISSUE TITLE
ClientLuaError returning wrong entities

### ISSUE THREAD

**Issue by wrefgtzweve** [danielga/gm_luaerror#40]
ClientLuaError returns completely random, seen it return basically anything including prop_physics entities.

![image](https://user-images.githubusercontent.com/69946827/155863426-0d554484-e75c-4023-9d6d-5d892bab01e3.png)
![image](https://user-images.githubusercontent.com/69946827/155863507-baca0897-db56-4950-a142-dc54eb429cb3.png)
![image](https://user-images.githubusercontent.com/69946827/155863509-b35eb086-4ae5-42ac-8498-bd8036bf1889.png)

**Comment by danielga** [comment]
What branch of Garry's Mod is this (main or x86-64)? What architecture is it (x86 or x64)?

**Comment by danielga** [comment]
Also, are you running the module on a dedicated server, listen server or as a client?

**Comment by brandonsturgeon** [comment]
Answering on behalf of @wrefgtzweve:

Dedicated server
OS: Ubuntu 18.04.5 LTS x86_64
Branch: x86-64

**Comment by danielga** [comment]
Okay, there's already a red flag there, you're running the module on the x86-64 branch, which is not officially supported. I'll try to have a look but not promising anything.

**Comment by tomekb530** [comment]
Can confirm, gmod x86-64 branch return weird entities instead of players

**Comment by danielga** [comment]
If you were using the `x86-64-support-sourcesdk` branch of `garrysmod_common`, the issue should be fixed for the x86-64 branch of Garry's Mod.

**Comment by brandonsturgeon** [comment]
Much appreciated!
