### ISSUE TITLE
ClientLuaError stack missing `short_src`

### ISSUE THREAD

**Issue by wrefgtzweve** [danielga/gm_luaerror#41]
Both hooks add the stack object, however they seem to be slightly different. I can't seem to get the `short_src` from the `ClientLuaError` hook stack at all. 

Clientside example:
![image](https://user-images.githubusercontent.com/69946827/156931878-22205e15-57ea-49a6-827e-d5dd46989e61.png)
![image](https://user-images.githubusercontent.com/69946827/156931904-a2393377-f3cf-40a8-a28c-0cfccd104abb.png)

Serverside example:
![image](https://user-images.githubusercontent.com/69946827/156931964-68afa34b-2a82-4866-a39e-f472c3b2ab4c.png)
![image](https://user-images.githubusercontent.com/69946827/156931980-0305526b-66dd-4425-ac98-8adbffcdf356.png)

Yet server side seems to have the short_src.

Might be intentional or just a limitation by gmod, in that case feel free to close it.

**Comment by danielga** [comment]
> Might be intentional or just a limitation by gmod, in that case feel free to close it.

It is indeed a limitation by Garry's Mod. All I receive from clientside errors are a single string, which I then parse into [stack level, function name, current line and source file.](https://github.com/danielga/gm_luaerror/blob/master/source/server.cpp#L100-L110)

**Comment by wrefgtzweve** [comment]
I figured, thanks for looking into it!
