### ISSUE TITLE
Rare issue with determining the Source File and Source Line

### ISSUE THREAD

**Issue by brandonsturgeon** [danielga/gm_luaerror#43]
While currently correct >99% of the time, it's technically possible to have a source file with a `:` in it.

The current implementation appears to split the string by all `:`'s, and assumes the first element is the File, and the second is the Line Number.

Instead, to cover all cases, it could split by only the _last_ `:` and make the same assumptions.

**Comment by danielga** [comment]
I improved the error parsing code and added some common test cases. Those tests don't have any specific cases involving your situation but the fix should still work in your case. Please give me a heads up if it does fail. [Here's the build.](https://github.com/danielga/gm_luaerror/releases/tag/1.5.8-rc1)

**Comment by brandonsturgeon** [comment]
Thank you! I'll give it a shot and report back.
