### ISSUE TITLE
"unable to obtain AdvancedLuaErrorReporter" when requiring module

### ISSUE THREAD

**Issue by CheezusChrust** [danielga/gm_luaerror#47]
As the title says, when I `require("luaerror")` I'm receiving the error in the title, alongside my server crashing immediately. Server is running on Windows Server 2019, GMod version is the latest version of the main branch. I am on the latest version of luaerror.

This only started happening after I updated the GMod server today (first time in around 3 months), if it helps.

My other installed modules:
https://github.com/Metastruct/gm_enginespew
https://github.com/FredyH/GWSockets
https://github.com/WilliamVenner/gmsv_reqwest

**Comment by CheezusChrust** [comment]
Just tested on a fresh server with no other modules installed, still happening. Hoping this can get looked at soon as I'm using a couple of addons that depend on this.

**Comment by brandonsturgeon** [comment]
After talking with them and some other gm_luaerror users, it seems like this issue is specific to windows (perhaps windows server, in particular), and is still present in the latest build.

**Comment by MoskalykA** [comment]
Problem also present on Windows 11

**Comment by danielga** [comment]
This should be fixed in [1.5.9-rc2](https://github.com/danielga/gm_luaerror/releases/tag/1.5.9-rc2).

**Comment by 766974616c79** [comment]
> This should be fixed in [1.5.9-rc2](https://github.com/danielga/gm_luaerror/releases/tag/1.5.9-rc2).

Everything is corrected for me, thank you <3
